### ISSUE TITLE
kramersmoyal: a meeting of packages

### ISSUE THREAD

**Issue by LRydin** [tee-lab/PyDaddy#25]
Dear Arshed, Ashwin, Shuaib, Jitesh, Danny, and Vishwesha,

I just came across your `PyDaddy` implementation, which looks pretty cool. I did not yet dive into your techniques to estimate the conditional moments, but I wanted to point you to my early implementation called [kramersmoyal](https://github.com/LRydin/KramersMoyal), which is based on a non-parametric kernel-density estimation of the KM coefficients. Maybe this is helpful for you as well. 

Check out as well [jumpdiff](https://github.com/LRydin/jumpdiff) where we go a bit further into studying higher-order KM coefficients and some measures for discontinuous trajectories.

Hope this helps in some/any way!

Cheers,
Leo

**Comment by arshednabeel** [comment]
Hey Leo!

Thanks for checking out our package! 

At the moment, we just use the empirical averages to estimate the conditional Kramers-Moyal moments. Since we also use sparse regression to fit the drift and diffusion functions, we are able to eliminate the bin-wise averaging step that's traditionally used.

Your approach of kernel-density estimation looks very interesting! We will definitely check this out for future iterations of PyDaddy: we are indeed thinking of implementing (at some point of time) alternate methods of estimating KM coefficients.

Thanks again for reaching out. Cheers,
Arshed
